pipeline {
    agent any

    tools {
    jdk 'JDK21'
    maven 'Maven-3.9'
}

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Sai048/microservice-1.git'
            }
        }

        stage('Clean') {
            steps {
                sh '''
                    for service in ecommerce-microservices/*/; do
                        if [ -f "$service/pom.xml" ]; then
                            echo "Cleaning $service"
                            mvn -f "$service/pom.xml" clean
                        fi
                    done

                '''
            }
        }

        stage('build') {
            steps {
                sh '''
                    for service in ecommerce-microservices/*/; do
                        if [ -f "$service/pom.xml" ]; then
                            echo "building $service"
                            mvn -f "$service/pom.xml" package -DskipTests
                        fi
                    done

                '''
            }
        }
    }
}