

pipeline {
    agent any

    tools {
        jdk 'JDK21'
        maven 'Maven-3'
    }

    environment {
        IMAGE_TAG = "${env.GIT_COMMIT.take(7)}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Sai048/microservice-1.git'
            }
        }

        stage('Clean') {
            steps {
                sh '''
                    for service in ecommerce-microservices/*/; do
                        if [ -f "$service/pom.xml" ]; then
                            echo "Cleaning $service"
                            mvn -f "$service/pom.xml" clean
                        fi
                    done
                '''
            }
        }

        stage('Maven Build') {
            steps {
                sh '''
                    for service in ecommerce-microservices/*/; do
                        if [ -f "$service/pom.xml" ]; then
                            echo "Building $service"
                            mvn -f "$service/pom.xml" package -DskipTests
                        fi
                    done
                '''
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                    echo "Docker image tag: $IMAGE_TAG"

                    for service in ecommerce-microservices/*/; do
                        if [ -f "$service/Dockerfile" ]; then

                            service_name=$(basename "$service")

                            echo "Building $service_name:$IMAGE_TAG"

                            docker build \
                                -t "$service_name:$IMAGE_TAG" \
                                "$service"

                        fi
                    done
                '''
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-credentials',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login \
                            -u "$DOCKER_USERNAME" \
                            --password-stdin
                    '''
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-credentials',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {
                    sh '''
                        for service in ecommerce-microservices/*/; do

                            if [ -f "$service/Dockerfile" ]; then

                                service_name=$(basename "$service")

                                echo "Tagging $service_name:$IMAGE_TAG"

                                docker tag \
                                    "$service_name:$IMAGE_TAG" \
                                    "$DOCKER_USERNAME/$service_name:$IMAGE_TAG"

                                echo "Pushing $DOCKER_USERNAME/$service_name:$IMAGE_TAG"

                                docker push \
                                    "$DOCKER_USERNAME/$service_name:$IMAGE_TAG"

                            fi

                        done
                    '''
                }
            }
        }


        stage('Clean Images') {
            steps {
                sh '''
                    docker image prune -a -f
                '''
            }
        }

        stage('Update Kubernetes Manifests') {
            steps {
                sh '''
                    rm -rf ecommerce-k8s-manifests

                    git clone https://github.com/Sai048/ecommerce-k8s-manifests.git

                    cd ecommerce-k8s-manifests

                    git config user.name "Sai_048"
                    git config user.email "saitejabellamkonda2002@example.com"


                    sed -i "s|image: sai048/config-server:.*|image: sai048/config-server:$IMAGE_TAG|g" deployments/deployment.yaml
                    sed -i "s|image: sai048/discovery:.*|image: sai048/discovery:$IMAGE_TAG|g" deployments/deployment.yaml
                    sed -i "s|image: sai048/products:.*|image: sai048/products:$IMAGE_TAG|g" deployments/deployment.yaml
                    sed -i "s|image: sai048/cart:.*|image: sai048/cart:$IMAGE_TAG|g" deployments/deployment.yaml

                    git add .
                    git commit -m "Update image tag to $IMAGE_TAG" || true
                    git push origin main
                '''
            }
        }
    }
}